//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HurlingApi.Models
{
    using System;
    using System.Collections.Generic;
    
    /// <summary></summary>
    public partial class League
    {
        /// <summary></summary>
        public League()
        {
            this.Teams = new HashSet<Team>();
        }
    
        /// <summary></summary>
        public int Id { get; set; }

        /// <summary></summary>
        public string Name { get; set; }

        /// <summary></summary>
        public DateTime NextFixtures { get; set; }

        /// <summary></summary>
        public byte Week { get; set; }
    
        /// <summary></summary>
        public virtual ICollection<Team> Teams { get; set; }
    }
}
