//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HurlingApi.Models
{
    using System;
    using System.Collections.Generic;

    /// <summary></summary>
    public partial class Position
    {
        /// <summary></summary>
        public Position()
        {
            this.Players = new HashSet<Player>();
        }

        /// <summary></summary>
        public int Id { get; set; }

        /// <summary></summary>
        public string Name { get; set; }

        /// <summary></summary>
        public virtual ICollection<Player> Players { get; set; }
    }
}
