//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HurlingApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamPlayer
    {
        public int Id { get; set; }
        public Nullable<int> TeamId { get; set; }
        public Nullable<int> PlayerId { get; set; }
    
        public Team Team { get; set; }
        public Player Player { get; set; }
    }
}
